
package accomplish.dto.account.balance.response;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

public class Info {

    @SerializedName("id")
    @Expose
    private Integer id;
    @SerializedName("program_id")
    @Expose
    private Integer programId;
    @SerializedName("base_bin_id")
    @Expose
    private Integer baseBinId;
    @SerializedName("status")
    @Expose
    private Boolean status;
    @SerializedName("type")
    @Expose
    private Integer type;
    @SerializedName("generation_type")
    @Expose
    private Integer generationType;
    @SerializedName("is_auto_generated")
    @Expose
    private Boolean isAutoGenerated;
    @SerializedName("number")
    @Expose
    private String number;
    @SerializedName("currency")
    @Expose
    private String currency;
    @SerializedName("points_bin_currency")
    @Expose
    private String pointsBinCurrency;
    @SerializedName("balance")
    @Expose
    private Double balance;
    @SerializedName("total_accounts_balances")
    @Expose
    private Double totalAccountsBalances;
    @SerializedName("total_accounts_available_balances")
    @Expose
    private Double totalAccountsAvailableBalances;
    @SerializedName("float_balance")
    @Expose
    private Double floatBalance;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getProgramId() {
        return programId;
    }

    public void setProgramId(Integer programId) {
        this.programId = programId;
    }

    public Integer getBaseBinId() {
        return baseBinId;
    }

    public void setBaseBinId(Integer baseBinId) {
        this.baseBinId = baseBinId;
    }

    public Boolean getStatus() {
        return status;
    }

    public void setStatus(Boolean status) {
        this.status = status;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Integer getGenerationType() {
        return generationType;
    }

    public void setGenerationType(Integer generationType) {
        this.generationType = generationType;
    }

    public Boolean getIsAutoGenerated() {
        return isAutoGenerated;
    }

    public void setIsAutoGenerated(Boolean isAutoGenerated) {
        this.isAutoGenerated = isAutoGenerated;
    }

    public String getNumber() {
        return number;
    }

    public void setNumber(String number) {
        this.number = number;
    }

    public String getCurrency() {
        return currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }

    public String getPointsBinCurrency() {
        return pointsBinCurrency;
    }

    public void setPointsBinCurrency(String pointsBinCurrency) {
        this.pointsBinCurrency = pointsBinCurrency;
    }

    public Double getBalance() {
        return balance;
    }

    public void setBalance(Double balance) {
        this.balance = balance;
    }

    public Double getTotalAccountsBalances() {
        return totalAccountsBalances;
    }

    public void setTotalAccountsBalances(Double totalAccountsBalances) {
        this.totalAccountsBalances = totalAccountsBalances;
    }

    public Double getTotalAccountsAvailableBalances() {
        return totalAccountsAvailableBalances;
    }

    public void setTotalAccountsAvailableBalances(Double totalAccountsAvailableBalances) {
        this.totalAccountsAvailableBalances = totalAccountsAvailableBalances;
    }

    public Double getFloatBalance() {
        return floatBalance;
    }

    public void setFloatBalance(Double floatBalance) {
        this.floatBalance = floatBalance;
    }

}
